minimumReleaseAgeExclude:
  - '@minecraft/server@2.11.0-beta.1.26.52-stable'
  - '@minecraft/server-ui@2.3.0-beta.1.26.52-stable'
  - '@minecraft/debug-utilities@1.0.0-beta.1.26.52-stable'
  - '@minecraft/server-admin@1.0.0-beta.1.26.52-stable'
