import { GameRule, PlayerWaypointsMode } from "@minecraft/server";

export const OPTIMISED_GAMERULE_SETUP = [
    { rule: GameRule.CommandBlockOutput, value: false },
    { rule: GameRule.DoDayLightCycle, value: false },
    { rule: GameRule.DoEntityDrops, value: false },
    { rule: GameRule.DoFireTick, value: false },
    { rule: GameRule.RecipesUnlock, value: false },
    { rule: GameRule.DoLimitedCrafting, value: true },
    { rule: GameRule.DoMobLoot, value: false },
    { rule: GameRule.DoMobSpawning, value: false },
    { rule: GameRule.DoTileDrops, value: false },
    { rule: GameRule.DoWeatherCycle, value: false },
    { rule: GameRule.DrowningDamage, value: false },
    { rule: GameRule.FallDamage, value: false },
    { rule: GameRule.FireDamage, value: false },
    { rule: GameRule.KeepInventory, value: true },
    { rule: GameRule.MobGriefing, value: false },
    { rule: GameRule.Pvp, value: false },
    { rule: GameRule.ShowCoordinates, value: false },
    { rule: GameRule.PlayerWaypoints, value: PlayerWaypointsMode.Off },
    { rule: GameRule.ShowDaysPlayed, value: false },
    { rule: GameRule.NaturalRegeneration, value: false },
    { rule: GameRule.TntExplodes, value: false },
    { rule: GameRule.SendCommandFeedback, value: false },
    { rule: GameRule.DoInsomnia, value: false },
    { rule: GameRule.RandomTickSpeed, value: 0 },
    { rule: GameRule.DoImmediateRespawn, value: true },
    { rule: GameRule.ShowDeathMessages, value: false },
    { rule: GameRule.SpawnRadius, value: 0 },
    { rule: GameRule.ShowTags, value: false },
    { rule: GameRule.FreezeDamage, value: false },
    { rule: GameRule.RespawnBlocksExplode, value: false },
    { rule: GameRule.ShowBorderEffect, value: false },
    { rule: GameRule.ShowRecipeMessages, value: false },
    { rule: GameRule.PlayersSleepingPercentage, value: 101 },
    { rule: GameRule.ProjectilesCanBreakBlocks, value: false },
    { rule: GameRule.TntExplosionDropDecay, value: false },
];
