/* SPDX-License-Identifier: GPL-3.0-or-later
 * ============================================================================
 * Commands Plus Plus
 * Copyright (C) 2024-2026 jeanmajid and contributors
 * https://github.com/jeanmajid/MCPE-Commands-plus-plus
 * ============================================================================
 *
 * This file is part of Commands Plus Plus.
 *
 * Commands Plus Plus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Commands Plus Plus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Commands Plus Plus. If not, see <https://www.gnu.org/licenses/>.
 */

import { existsSync } from "fs";
import { readFile, writeFile } from "fs/promises";

import { TOP_AUTOGENERATED_HEADER, BOTTOM_AUTOGENERATED_HEADER } from "../constants/header.js";

export async function writeToDocsFile(filePath: string, content: string): Promise<void> {
    filePath = filePath + ".md";

    let fileContents = [];
    if (!existsSync(filePath)) {
        fileContents = [`${TOP_AUTOGENERATED_HEADER}\n${BOTTOM_AUTOGENERATED_HEADER}\n`];
    } else {
        fileContents = (await readFile(filePath, { encoding: "utf-8" })).split("\n");
    }

    let topAutogeneratedHeaderLine = fileContents.findIndex((line) =>
        line.startsWith(TOP_AUTOGENERATED_HEADER)
    );

    let bottomAutogeneratedHeaderLine = fileContents
        .slice(topAutogeneratedHeaderLine)
        .findIndex((line) => line.startsWith(BOTTOM_AUTOGENERATED_HEADER));

    if (topAutogeneratedHeaderLine === -1) {
        topAutogeneratedHeaderLine = 0;
        bottomAutogeneratedHeaderLine = 0;
    }

    const fileData = [
        ...fileContents.slice(0, topAutogeneratedHeaderLine),
        TOP_AUTOGENERATED_HEADER,
        "",
        content,
        "",
        BOTTOM_AUTOGENERATED_HEADER,
        ...fileContents.slice(bottomAutogeneratedHeaderLine + 1, fileContents.length),
    ];

    writeFile(filePath, fileData.join("\n"));
}
